### ISSUE TITLE
Solve electrical connectiosn to plug in router and camera

### ISSUE THREAD

**Issue by miguelriemoliveira** [miguelriemoliveira/lemonbot#19]

**Comment by bernardomig** [comment]
The electrical connections are done.

The router can be accessed via wlan, and the ip address of the nuc is 192.168.1.100.
The camera is also connected and working. 

A cable harness was done to supply both the camera, ptu and router with 12V.

This is the wire connections:
[![30762867_1144302832377969_6865260950686007296_n.jpg](https://s7.postimg.cc/63hgrsm0b/30762867_1144302832377969_6865260950686007296_n.jpg)](https://postimg.cc/image/9n3ehlopz/)

**Comment by miguelriemoliveira** [comment]
Looks good. The network passwd shoud be somewhere (README file?)

Miguel

**Comment by bernardomig** [comment]
The details on how to connect to the lemonbot are on the README.md
