### ISSUE TITLE
Create the (un)calibrated xacro file

### ISSUE THREAD

**Issue by bernardomig** [miguelriemoliveira/lemonbot#2]
# Goal
- create xacro with `<unless>` calibrated
- get the calibration of both the camera and laser from xacro in `calibration/hand_in_eye.urdf.xacro`

**Comment by bernardomig** [comment]
Calibration urdf done. The following explains how this calibration works.

# Calibration files

Both the camera calibration and laser calibration are stored in 2 yaml files: `camera_calibration.yaml` and `laser_calibration.yaml` in `lemonbot_calibration/calibration`.

This files look like:

```yaml
xyz: [0.03, -0.1, 0.1]
rpy: [-1.57, 0, 0]
```

# Xacro file

When the lemonbot xacro is processed, both files can be loaded using the `calibrated` option. This is an argument of `load_urdf.launch`. 

If the `calibration` option is false, then the transformations are null. If it is true, then both calibrations are loaded and put into the robot_description. 

The `load_urdf.launch` alse was the 2 following arguments, to specifying the load path of the files. The default path is `lemonbot_calibration/calibration/xxxxx_calibration.yaml`.

```xml
<arg name="camera_calibration_file" default="$(find lemonbot_calibration)/calibration/camera_calibration.yaml" />
<arg name="laser_calibration_file" default="$(find lemonbot_calibration)/calibration /laser_calibration.yaml" />
```

**Comment by miguelriemoliveira** [comment]
Hi @bernardomig 

great. These instructions (or part of them) are relevant for calibrating the system?

If so they should be in the README.

If you tested and validated you can close the issue.

**Comment by bernardomig** [comment]
@miguelriemoliveira 

They are for storing the calibration data (xyz and rpy). I'll add to the README
