### ISSUE TITLE
Create accumulator node

### ISSUE THREAD

**Issue by bernardomig** [miguelriemoliveira/lemonbot#5]
Create a node that accumulates point cloud messages

**Comment by miguelriemoliveira** [comment]
Here's one example 

https://github.com/miguelriemoliveira/RustBot/blob/master/rustbot_accumulate_point_clouds/src/accumulatepointcloud.cpp

**Comment by miguelriemoliveira** [comment]
Test: use joint state publisher to move mannualy the ptu around. View in rviz the accumulated point cloud being generated.
